/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package ch.nomisp.confluence.publisher

import org.gradle.testfixtures.ProjectBuilder
import spock.lang.Specification

/**
 * A simple unit test for the 'ch.nomisp.confluence.publisher' plugin.
 */
class ConfluencePublisherPluginTest extends Specification {
    def "When the plugin is applied, then the extension and the task is available"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply(ConfluencePublisherPlugin.packageName)
//        project.plugins.apply("ch.nomisp.confluence.publisher")

        then:
        project.extensions.findByName(ConfluencePublisherPlugin.CONFLUENCE_PUBLISHING_EXTENSION) != null
        project.tasks.findByName(ConfluencePublisherPlugin.CONFLUENCE_PUBLISHING_TASK) != null
    }
}
