= Documentation of the confluence-publisher-plugin project
:doctype: book
:page-layout!:
:toc: left
:toclevels: 2
:sectanchors:
:sectlinks:
:sectnums:
//:imagesdir: ../images
//:includedir: _includes

[#user-toc]
== About the Confluence publisher plugin
The Confluence publisher Gradle plugin is a plugin to convert documentation written in asciidoc to Confluence compatible XHTML
and publish the documentation to Confluence.

This plugin is licensed under https://opensource.org/licenses/Apache-2.0[Apache-2.0] license.
The source code can be found https://github.com/nomisp/confluence-publisher-plugin[here].

For further information about how to use the plugins, read the User guide.

If you're a developer, check out the developer documentation on how to setup and build the project.

== User guide
Learn how to use the Confluence publisher Gradle plugin in the <<index/user-guide.adoc#, User guide>>.

== Release notes
Check out the <<index/release-notes.adoc#, release notes>> to see the changes.

== Developer documentation
Find out how to setup and build the project in the <<index/developer-doc.adoc#, Developer documentation>>.
