= Confluence publisher Gradle plugin Developer documentation
:doctype: book
:page-layout!:
:toc: left
:toclevels: 2
:sectanchors:
:sectlinks:
:sectnums:

== Setup the development environment
=== Clone the repository
First of all clone the Git repository to a local directory.
[source, bash]
----
git clone https://github.com/nomisp/confluence-publisher-plugin.git
----

=== Import into IntelliJ
To import the project into IntelliJ, just go to: File > New... > Project from Existing Sources...

Choose the location of the local directory and continue importing from the Gradle model.

=== Local build
The project makes use of a Gradle wrapper. To build the project just make use of the standard tasks. e.g.
[source, bash]
----
gradlew clean build
----

To run the tests (unit and functional tests) execute:
[source, bash]
----
gradlew check
----

[NOTE]
In order run the functional tests, Confluence cloud can be used (see https://nomisp.atlassian.net/wiki/spaces/GRADLE/pages/2555905/Functional+Tests[Confluence-Cloud])

[WARNING]
For the functional tests don't use the Confluence-API token in plain text.
Therefore the credentials-plugin can be used to add the token into the encrypted properties file and retrieve it afterwards from there.
The description of the credentials plugin can be found https://github.com/etiennestuder/gradle-credentials-plugin[here].
[source, bash]
----
gradlew addCredentials --key confluenceToken --value <tokenValue>
----

== Locally try out the plugins
To try out the plugin in another project, the plugin can be published to the local maven repository.
[source, bash]
----
gradlew publishToMavenLocal
----
In the console output the version will be printed out and can be used in the projects where they should be tried out.
