= Confluence publisher Gradle plugin User guide
:doctype: book
:page-layout!:
:toc: left
:toclevels: 2
:sectanchors:
:sectlinks:
:sectnums:

== The Confluence publisher plugin
The Confluence publisher plugin suite is a plugin to convert documentation written in
asciidoc into the Confluence format.
The converted documentation can be directly published to Confluence.
This plugin makes use of the https://github.com/confluence-publisher/confluence-publisher[confluence-publisher] project
and is a conversion of that Maven plugin to Gradle.

To use the plugin make use of the Gradle plugin DSL.
[source, groovy]
----
plugins {
    id 'ch.nomisp.confluence.publisher' version '<version>'
}
----

== Available tasks
The Confluence publisher plugin provides one single task *publishToConfluence*.
This task converts the .adoc pages to the Confluence format.

== Configuration of the 'publishToConfluence' task
The task can be configured with the following properties:


|===
|Property |Description |Constraint

|asciidocRootFolder
|The documentation root folder with the AsciiDoc file structure.
|mandatory

|confluencePublisherBuildFolder
|Column 2, row 2
|Column 3, row 2

|rootConfluenceUrl
|Column 2, row 3
|Column 3, row 3

|spaceKey
|Column 2, row 4
|Column 3, row 4

|ancestorId
|Column 2, row 5
|Column 3, row 5

|username
|Column 2, row 6
|Column 3, row 6

|password
|The password of the user to use for publishing.

Note: when publishing to Confluence Cloud, an API token generated via the corresponding Atlassian account has to be used as password.

Note: when publishing to on-premise Confluence with an API token, leave the username empty ("").
|Column 3, row 7

|Column 1, row 8
|Column 2, row 8
|Column 3, row 8
|===


Example:
[source, groovy]
----
confluencePublisher {
    asciiDocRootFolder = tasks.asciidoctor.sourceDir
    confluencePublisherBuildFolder = file("${buildDir}/docs/confluence")
    rootConfluenceUrl = 'https://myconfluence.url.com'
    spaceKey = 'MySpace'
    ancestorId = 3774579
    username = 'MyConfluenceUser'
    password = 'MySecretPassword'
    notifyWatchers = false
}
----
